# Package Overview
package_name: classification_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict
target: isHigher

pipeline_name: classification_model
pipeline_save_file: classification_model_output_v

features:
  - Open
  - Close
  - High
  - Low
  - Volume

# set train/test split
test_size: 0.2

# to set the random seed
random_state: 0

# regularization paramater
C: 0.0005

# Weithing approach
class_weight: balanced